import type { ImgHTMLAttributes } from "react";
import { imageSet, type ImageName } from "@/lib/images";

type Props = Omit<ImgHTMLAttributes<HTMLImageElement>, "src" | "srcSet"> & {
  name: ImageName;
  sizes: string;
  priority?: boolean;
};

/**
 * Responsive <picture>: WebP variants (generated by
 * scripts/optimize-images.mjs) with the original JPEG as fallback.
 */
export default function Pic({
  name,
  sizes,
  priority = false,
  alt = "",
  ...rest
}: Props) {
  const { src, srcSet, width, height } = imageSet(name);
  return (
    <picture>
      {srcSet ? <source type="image/webp" srcSet={srcSet} sizes={sizes} /> : null}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={src}
        alt={alt}
        width={width || undefined}
        height={height || undefined}
        loading={priority ? "eager" : "lazy"}
        fetchPriority={priority ? "high" : undefined}
        decoding="async"
        draggable={false}
        {...rest}
      />
    </picture>
  );
}
